name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: make
