name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: 3DeSktop.3dsx
        path: 3DeSktop.3dsx
